<?php

CModule::AddAutoloadClasses('estate', array(
    'FieldTypeRefCheckboxes'                       => 'classes/general/fieldtyperefcheckboxes.php',
    'FieldTypeRefSelectMulti'                      => 'classes/general/fieldtyperefselectmulti.php',
    'FieldTypeFile'                                => 'classes/general/fieldtypefile.php',
    'CIBlockPropertyEstate'                        => 'classes/general/prop_estate.php',
    'XmlImport'                                    => 'classes/general/xmlimport.php',
    'Bitrix\Estate\DataManager'                    => 'lib/datamanager.php',
    '\Bitrix\Estate\DataManager'                   => 'lib/datamanager.php',
    'Bitrix\Estate\BaseEstate'                     => 'lib/baseestate.php',
    '\Bitrix\Estate\BaseEstate'                    => 'lib/baseestate.php',
    'Bitrix\Estate\EstateTable'                    => 'lib/estate.php',
    '\Bitrix\Estate\EstateTable'                   => 'lib/estate.php',
    'Bitrix\Estate\EstateObjectTable'              => 'lib/estateobject.php',
    '\Bitrix\Estate\EstateObjectTable'             => 'lib/estateobject.php',
    'Bitrix\Estate\EstateBuildingTable'            => 'lib/estatebuilding.php',
    '\Bitrix\Estate\EstateBuildingTable'           => 'lib/estatebuilding.php',
    'Bitrix\Estate\EstateSectionTable'             => 'lib/estatesection.php',
    '\Bitrix\Estate\EstateSectionTable'            => 'lib/estatesection.php',
    'Bitrix\Estate\EstateFloorTable'               => 'lib/estatefloor.php',
    '\Bitrix\Estate\EstateFloorTable'              => 'lib/estatefloor.php',
    'Bitrix\Estate\EstateFlatTable'                => 'lib/estateflat.php',
    '\Bitrix\Estate\EstateFlatTable'               => 'lib/estateflat.php',
    'Bitrix\Estate\EstatePremiseTable'             => 'lib/estatepremise.php',
    '\Bitrix\Estate\EstatePremiseTable'            => 'lib/estatepremise.php',
    'Bitrix\Estate\EstateObjectPanoTable'          => 'lib/estateobjectpano.php',
    '\Bitrix\Estate\EstateObjectPanoTable'         => 'lib/estateobjectpano.php',
    'Bitrix\Estate\EstateRefCitiesTable'           => 'lib/estaterefcities.php',
    '\Bitrix\Estate\EstateRefCitiesTable'          => 'lib/estaterefcities.php',
    'Bitrix\Estate\EstateRefDistrictsTable'        => 'lib/estaterefdistricts.php',
    '\Bitrix\Estate\EstateRefDistrictsTable'       => 'lib/estaterefdistricts.php',
    'Bitrix\Estate\EstateRefFeaturesTable'         => 'lib/estatereffeatures.php',
    '\Bitrix\Estate\EstateRefFeaturesTable'        => 'lib/estatereffeatures.php',
    'Bitrix\Estate\EstateRefFlatStatusesTable'     => 'lib/estaterefflatstatuses.php',
    '\Bitrix\Estate\EstateRefFlatStatusesTable'    => 'lib/estaterefflatstatuses.php',
    'Bitrix\Estate\EstateRefFlatTypesTable'        => 'lib/estaterefflattypes.php',
    '\Bitrix\Estate\EstateRefFlatTypesTable'       => 'lib/estaterefflattypes.php',
    'Bitrix\Estate\EstateRefRoomsTable'            => 'lib/estaterefrooms.php',
    '\Bitrix\Estate\EstateRefRoomsTable'           => 'lib/estaterefrooms.php',
    '\Bitrix\Estate\EstateRefPremiseStatusesTable' => 'lib/estaterefpremisestatuses.php',
    'Bitrix\Estate\EstateRefPremiseStatusesTable'  => 'lib/estaterefpremisestatuses.php',
    'Bitrix\Estate\EstateRefPremiseTypesTable'     => 'lib/estaterefpremisetypes.php',
    '\Bitrix\Estate\EstateRefPremiseTypesTable'    => 'lib/estaterefpremisetypes.php',
    'Bitrix\Estate\EstateRefStagesTable'           => 'lib/estaterefstages.php',
    '\Bitrix\Estate\EstateRefStagesTable'          => 'lib/estaterefstages.php',
    'Bitrix\Estate\EstateRefSubwayTable'           => 'lib/estaterefsubway.php',
    '\Bitrix\Estate\EstateRefSubwayTable'          => 'lib/estaterefsubway.php',
    'Bitrix\Estate\EstateRefOptionsTable'          => 'lib/estaterefoptions.php',
    '\Bitrix\Estate\EstateRefOptionsTable'         => 'lib/estaterefoptions.php',
    'Bitrix\Estate\Common'                         => 'lib/common.php',
    '\Bitrix\Estate\Common'                        => 'lib/common.php',
    'Bitrix\Estate\EstateSearch'                   => 'lib/estatesearch.php',
    '\Bitrix\Estate\EstateSearch'                  => 'lib/estatesearch.php',
));

